.github/workflows/release.yml, chart/values.yaml
Should be merged only when the https://github.com/flanksource/canary-checker/pull/449 is merged and helm chart is published
=> chore: helm fixes

cmd/server.go, go.mod, go.sum, utils/http.go
Bump duty version in `go.mod` once https://github.com/flanksource/duty/pull/13 is merged.
=> feat: serve openapi schemas from duty

api/check.go, config_done_test.go, db/evidences.go, evidence_done_test.go, jobs/evidence_script_cel.go, jobs/evidence_script_cel_test.go
* cel expression didn't not env var about the check. Now it's added.
* added test for incident done definition using checks.
* fixed bug in previous done definition using config test.
Resolves: https://github.com/flanksource/incident-commander/issues/281
=> fix: support done expression for checks

auth/templates.go, events/events.go
* `last_attempt` was never saved. It was always null.
* Resolves: https://github.com/flanksource/flanksource-ui/issues/1153
=> Fix: event queue last_attempt

api/upstream.go, canary/controllers.go, db/canaries.go
so the canary agent doesn't receive entire canaries on every pull request
=> feat: return a cursor timestamp to agent on canary request

events/event_consumer.go, events/events.go, events/notifications.go
- `.Listen()` was called multiple times for the same consumer
- resource id in notifications job history
=> fix: event consumer

mail/mailer.go, notification/shoutrrr.go
Resolves: https://github.com/flanksource/incident-commander/issues/551
=> feat: use gomail for shoutrrr SMTP

cmd/server.go, events/notifications.go, go.mod, notification/context.go, notification/metrics.go, notification/shoutrrr.go
Resolves: https://github.com/flanksource/incident-commander/issues/555
=> feat: add metrics for notifications

auth/middleware.go, cmd/root.go, db/models/team.go, db/people.go, rbac/middleware.go, rbac/middleware_test.go
=> feat: mapping identities to roles & teams

api/upstream.go, jobs/upstream.go, upstream/controllers.go, upstream/reconcile_test.go
Distinguishes between the tables a mc agent should reconcile and the tables a mc upstream should allow reconciliation.
Fixes
=> fix: allowed reconciliation tables

events/event_queue.go, upstream/events.go
resolves: https://github.com/flanksource/mission-control/issues/897
the batch size and num of consumers that were set when registering an async handler were ignored.
=> fix: set batchsize and consumer count in async event queue handler

go.mod, go.sum, hack/generate-schemas/go.mod, hack/generate-schemas/go.sum
fixes: `config_detail` view. Returns health and ready.
=> chore: bump duty

playbook/controllers.go
when rendering playbook parameters, set the currently logged in user as the creator of the dummy run so it's accessible in the templates.
=> feat: set the current user when templating playbook parameters

api/global.go, cmd/root.go, cmd/server.go, echo/kube_config_download.go, notification/events.go
We need URL of the frontend and the backend.
Frontend is used to form links in the notifications.
Backend is used to as server url when forming kubeconfig.
=> feat: public url

echo/kube_config_download.go, echo/serve.go
* when reading token `\n` was appended and Auth header value would be invalid
* in the kubeconfig set user instead of token so kubectl doesn't ask for basic auth
=> fix: kubeproxy & kubeconfig

rbac/middleware.go
Queries like POST catalog/summary are failing as they are marked as read but we are overriding it always by extracting from Method
=> fix: override action if default is unset

echo/serve.go, events/event_queue.go, events/ring.go, go.mod, go.sum, notification/events.go, playbook/events.go
resolves: https://github.com/flanksource/mission-control/issues/1232
merge after: https://github.com/flanksource/postq/pull/10
=> feat: expose events processed history on /event-log endpoint

Makefile, go.mod, go.sum, notification/events.go, notification/send.go, notification/shoutrrr.go, notification/slack.go, notification/template.go, notification/templates/check.failed, notification/templates/check.passed, playbook/actions/notification.go
resolves: https://github.com/flanksource/mission-control/issues/923
- needed quite a bit of refactoring because the templating of the notification title & body needs to be pushed to the very end of the pipeline instead of the very beginning. This is because now we need to template the message only after we've figured out the shoutrrr service we're sending to.
=> feat: use new Slack module to send slack notifications

db/notifications.go, go.mod, go.sum, notification/context.go, notification/events.go, notification/notification_test.go
* check silences -> repeat interval -> rate limits
* new metrics
* `notification_silenced`
* `notification_skipped_by_repeat_interval`
resolves: https://github.com/flanksource/mission-control/issues/1387
=> feat: save unsent notification using the new postgresql function

.github/workflows/lint.yml, notification/context.go, notification/events.go, notification/notification_test.go, notification/send.go, notification/shoutrrr.go
resolves: https://github.com/flanksource/mission-control/issues/1395
=> feat: add notification body on send errors & add test to ensure notification.send events are retried

playbook/controllers.go
`CreateTemplateEnv` uses the spec from the run
resolves: https://github.com/flanksource/mission-control/issues/1441
=> fix: playbook parameters rendering

go.mod, go.sum, jobs/upstream.go, push/push_test.go, push/topology.go
Depends on: https://github.com/flanksource/duty/pull/1088
=> fix: deletion logic in push topology

go.mod, go.sum, notification/cel.go, notification/events.go, notification/notification_test.go, notification/send.go, notification/shoutrrr.go, notification/shoutrrr_test.go, notification/suite_test.go, notification/template.go, playbook/actions/actions.go
resolves: https://github.com/flanksource/mission-control/issues/1446
This happend for SMTP notifications.
We need to first template and then convert the markdown to HTML.
Else the `markdown -> HTML` conversion will break all the go templating logic.
=> fix: templating of notifications for SMTP

notification/notification_test.go, playbook/runner/runner.go, rbac/middleware.go
resolves: https://github.com/flanksource/mission-control/issues/1463
when the agent wasn't found, we were wrapping a `nil` error.
The consumer would then exit without progressing and get stuck in a loop.
=> fix: playbook run loop

cmd/server.go, go.mod, go.sum, rbac/init.go
resolves: https://github.com/flanksource/mission-control/issues/1469
=> feat: RBAC live policy change on permissions update

events/event_queue.go
resolves: https://github.com/flanksource/duty/issues/1105
=> feat: trim down on extraneous calls to ConsumeUntilEmpty in event consumers

go.mod, go.sum, notification/job.go, notification/notification_test.go
merge after: https://github.com/flanksource/duty/pull/1191
=> test: notification wait for

jobs/jobs.go
resolves: https://github.com/flanksource/duty/issues/1200
=> fix: use a single job instance for pull playbook actions this is to maintain retention

db/notifications.go, notification/events.go
the dedup window of 24hrs was only applied when saving silenced notifications.
for repeated notifications, we were still using 1m
=> fix: dedup window for unsent notifications

notification/job.go, notification/notification_test.go
resolves: https://github.com/flanksource/mission-control/issues/1643
for some errors, we never incremented the retries count. so the job keep looping.
and over time, new job runs kept piling up.
=> fix: error handling in pending notifications processor

Makefile, cmd/server.go, fixtures/playbooks/runs-on-simple.yaml, jobs/jobs.go, jobs/playbook.go, playbook/jobs.go
dependsOn: https://github.com/flanksource/duty/pull/1219
resolves: https://github.com/flanksource/mission-control/issues/1671
```
Agent: my machine
upstream: aws demo
playbook_action_pull_lag_bucket{agent="aditya-desktop",upstream="https://incident-commander.demo.aws.flanksource.com/api",le="100"} 0
playbook_action_pull_lag_bucket{agent="aditya-desktop",upstream="https://incident-commander.demo.aws.flanksource.com/api",le="200"} 2
playbook_action_pull_lag_bucket{agent="aditya-desktop",upstream="https://incident-commander.demo.aws.flanksource.com/api",le="500"} 2
playbook_action_pull_lag_bucket{agent="aditya-desktop",upstream="https://incident-commander.demo.aws.flanksource.com/api",le="1000"} 3
playbook_action_pull_lag_bucket{agent="aditya-desktop",upstream="https://incident-commander.demo …
```
=> feat: add metrics for playbook push pull

cmd/server.go, rbac/init.go
merge after: https://github.com/flanksource/duty/pull/1247
resolves: https://github.com/flanksource/mission-control/issues/1707
=> feat: sync team_members with casbin_rules

api/v1/playbook_actions.go, config/crds/mission-control.flanksource.com_playbooks.yaml, config/schemas/playbook-spec.schema.json, config/schemas/playbook.schema.json, playbook/actions/ai.go
resolves: https://github.com/flanksource/mission-control/issues/1710
=> feat: AI action draft mode

echo/serve.go
Duty uses it to handling caching of resource selectors
resolves: https://github.com/flanksource/mission-control/issues/1750
=> fix: add RLS enforcement indicator to the context.

notification/job.go
This would happen on rare ocassions where the `SyncCRDstatus` job would run before kopper initialization completed.
resolves: https://github.com/flanksource/mission-control/issues/1738
=> fix: prevent panic when reconciler isn't initialized

notification/send.go
when notification is sent from a playbook, we don't have an actual notification spec.
=> fix: panic on slack notification send

db/connections.go, db/incidents.go, db/notifications.go
resolves: https://github.com/flanksource/mission-control/issues/1789
ran into this when deleting a notification crd got stuck.
notification_send_history had foreign key to playbook_runs.
=> fix: soft delete on CRD delete

pkg/clients/git/connectors/git_access_token.go
```
ERROR 2025-02-10T08:42:13.582446236Z [resource.labels.containerName: mission-control] panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3b31815] goroutine 200 [running]: go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1() /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.28.0/trace/span.go:398 +0x25 go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026104e0, {0x0, 0x0, 0xc001370380?}) /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.28.0/trace/span.go:436 +0xa62 panic({0x62232e0?, 0xc02b240?}) /usr/local/go/src/runtime/panic.go:785 +0x132 github.com/flanksource/incident-commander/pkg/clients/git/connectors.(*GitAccessTokenClient).OpenPullRequest(0xc00075d1f0, {{{0x8271a10, …
```
=> fix: panic on pr creation

cmd/root.go, cmd/server.go, echo/serve.go
@moshloop @adityathebe Should be put the shutdown and exit in logger.Fatalf ? or keep it the way it is right now ?
=> chore: shutdown and exit in fatal scenarios

api/v1/notification_types.go, api/v1/zz_generated.deepcopy.go, config/crds/mission-control.flanksource.com_notifications.yaml, config/schemas/notification.schema.json, db/notifications.go, fixtures/notifications/config-health.yaml
repeatGroup (crd) was mapped to GroupByHash.
RepeatGroup was originally meant for different purpose.
Removing it for now as we aren't using it anywhere.
=> fix: use waitForGroup in CRD

db/notifications.go
resolves: https://github.com/flanksource/mission-control/issues/1863
=> fix: do not delete notification send history linked to playbook runs

playbook/webhook.go
```
{"time":"2025-03-14T08:44:12.280486736Z","level":"ERROR","msg":"could not find secret /clerk-api: the server could not find the requested resource","cod
e":"internal","error":"Internal error."}
{"time":"2025-03-14T08:44:12.280651013Z","level":"ERROR","msg":"Internal Server Error","request":{"time":"2025-03-14T08:44:12.272882377Z","method":"POST
","host":"mc.org-puirhxj5j7oz.workload-prod-eu-01.flanksource.com","path":"/playbook/webhook/suspend-tenant","query":"","params":{"webhook_path":"suspen
```
=> fix: add namespace context for webhook playbook

api/notifications.go, api/v1/playbook_actions.go, artifacts/artifacts.go, artifacts/controllers.go, artifacts/jobs.go, connection/controllers.go, notification/send.go, playbook/actions/gitops.go, playbook/actions/http.go, playbook/actions/sql.go, playbook/runner/artifacts.go, playbook/runner/runner.go
resolves: https://github.com/flanksource/mission-control/issues/638
=> feat: permission for connection

playbook/run_consumer.go, rbac/adapter/permission.go
We didn't have a corresponding ABAC rule for connection objects.
=> fix: permission for connections

playbook/jobs.go, playbook/run_consumer.go
that syntax isn't supported in v14
=> fix: run consumer sql query

notification/events.go
The notification context was missing permission subject, which resulted in a connection read authorization error.
=> fix: notification read connection permission

playbook/actions/http.go, playbook/playbook_test.go, playbook/testdata/action-http-authorized.yaml, playbook/testdata/action-http-unauthorized.yaml, playbook/testdata/connections/httpbin.yaml, playbook/testdata/permissions/allow-john-connection.yaml, playbook/testdata/permissions/allow-playbook-connection.yaml
Ensure that a playbook can read a connection only when it has the `read` permission.
=> test: Playbook permissions

playbook/actions/ai.go, playbook/playbook_test.go
seeings a few unmarshal errors
`failed to unmarshal diagnosis report: invalid character 'y' in literal null (expecting 'u')`
=> fix: add context to ai action error

.gitignore, pkg/clients/git/connectors/git_access_token.go, pkg/clients/git/connectors/git_ssh.go, utils/dir.go
This is because in MacOS, the temp dir can be "/var/folders" which is a blacklisted path by DoubleStart()
=> fix: create git clones in relative ".git-clones" dir not in temp dir

notification/cel.go, notification/events.go, notification/job.go, notification/send.go
resolves: https://github.com/flanksource/mission-control/issues/2066
dependsOn: https://github.com/flanksource/duty/pull/1423
=> feat: save resource health and status in notification send history

echo/serve.go, go.mod, go.sum, incidents/rules.go
Serve from mission control instead of forwarding to canary-checker because of RLS.
=> feat: Topology query
