flanksource/mission-control

ui/package-lock.json
ui/package.json
ui/src/index.js

Requires this PR in `flanksource-ui` to be merged first, and then the version number for that package in `/ui/package.json` probably needs to be updated as well:
https://github.com/flanksource/flanksource-ui/pull/251

fix: Incorrect import path. Bump up react-router-dom version

---

api/types.go
responder/config_sync.go

feat: Add support for defaults and values in team spec

---

db/migrations/004_incidents.sql
db/migrations/099_post-seed.sql
db/migrations/104_incident_history_triggers.sql

feat: add database triggers for incident history

---

db/components.go
jobs/team_components.go
teams/teams.go

chore: minor improvements for team components job

---

auth/client.go
auth/middleware.go
cmd/server.go
db/init.go
db/postgrest.go

Merge with: https://github.com/flanksource/incident-commander-chart/pull/24

feat: inject jwt token for postgrest proxy

---

snapshot/controllers.go
snapshot/dump.go

chore: support .log and .json for logs in snapshot

---

auth/middleware.go
cmd/server.go
utils/hash.go
utils/rand.go
utils/rand_test.go

Closes https://github.com/flanksource/incident-commander/issues/238
Closes https://github.com/flanksource/incident-commander/issues/257

feat: allow basic auth for all endpoints

---

cmd/server.go

Fixes: https://github.com/flanksource/incident-commander/issues/91

feat: add health check endpoint

---

db/components.go
go.sum

fix: handle empty parent ids for topology snapshot

---

api/upstream.go
db/templates.go
go.mod
go.sum

chore: bump duty and use Topology model

---

responder/config_sync.go
responder/jira/config.go
responder/msplanner/config.go
responder/responders.go

chore: rename config_type to config_class

---

config_done_test.go
suite_test.go

Resolves: https://github.com/flanksource/incident-commander/issues/146

added test for config done definition

---

api/upstream.go
cmd/root.go
db/agents.go
db/templates.go
events/upstream_push.go
go.mod
go.sum
upstream/controllers.go
upstream/upstream_test.go

Depends on: https://github.com/flanksource/duty/pull/154
Fixes: https://github.com/flanksource/incident-commander/issues/341

feat: auto create agent for upstream push

---

events/events.go

Resolves: https://github.com/flanksource/incident-commander/issues/358

fix: event consumer query

---

api/config.go
db/evidences.go
evidence_done_test.go
jobs/evidence_script_cel.go

Resolves: https://github.com/flanksource/config-db/issues/231

support config analysis as done definition

---

auth/templates.go
db/evidences.go
db/incidents.go
evidence_done_test.go

Resolves: https://github.com/flanksource/incident-commander/issues/398
Resolves: https://github.com/flanksource/incident-commander/issues/402

fix: empty script in evidence done def

---

responder/config_sync.go
responder/jira/config.go
responder/msplanner/config.go
responder/responders.go

Resolves: https://github.com/flanksource/flanksource-ui/issues/1218

fix: config type and config class in responder configs

---

api/event.go
cmd/root.go
events/events.go
events/responder.go
go.mod
go.sum

Depends on: https://github.com/flanksource/duty/pull/186

refactor: add priority to event handling and improve query

---

events/event_consumer.go
events/notifications.go
events/responder.go
events/teams.go
events/upstream_push.go

@moshloop FYI
Self-merging this to deploy the fix ASAP

fix: remove loop variable reference bug

---

go.mod
go.sum
incident_rules_test.go

@moshloop Minor test fix, self-merging

ci: fix system user for incident rule test

---

jobs/event_queue.go
jobs/jobs.go

Resolves: https://github.com/flanksource/incident-commander/issues/411

feat: add an event_queue cleaning job

---

auth/controllers.go

feat: add database and host name to whoami endpoint

---

api/team.go
auth/clerk_client.go
auth/middleware.go
auth/utils.go
db/people.go
go.mod
go.sum

Fixes: #501 
Depends on: https://github.com/flanksource/duty/pull/254

chore: use external_id to store clerk id

---

events/notifications.go
notification/shoutrrr.go

Resolves: https://github.com/flanksource/incident-commander/issues/514

feat: use default SMTP credential

---

events/event_queue.go
events/notifications.go
events/responder.go

Resolves: https://github.com/flanksource/incident-commander/issues/563

fix: handle conflicts when saving new events to the event_queue table

---

cmd/root.go
mail/mailer.go
notification/shoutrrr.go

Resolves: https://github.com/flanksource/incident-commander/issues/552

feat: add email from name flag

---

events/event_queue.go

Resolves: https://github.com/flanksource/incident-commander/issues/540

fix: when sync event fails, update the event's attempt metadata

---

db/job_history.go
jobs/job_history_cleanup.go
upstream/reconcile.go

* don't keep more than the last 3 successful and 10 unsuccessful jobs of job name, resource id combo

feat: clean old job histories

---

cmd/root.go
db/postgrest.go

https://github.com/flanksource/duty/issues/286

feat: add a max limit on the number of rows that postgrest can return

---

api/playbook.go
db/playbooks.go
playbook/controllers.go
playbook/playbook.go
playbook/playbook_test.go

* only return the playbook id & name on /playbook/list

fix: playbook list when the selector has no tags

---

auth/clerk_client.go

chore: sync clerk role with rbac on auth

---

fixtures/playbooks/upgrade-eks-cluster.yaml
playbook/playbook.go
playbook/playbook_test.go
playbook/run_consumer.go
playbook/runner.go

resolves: https://github.com/flanksource/incident-commander/issues/621

fix: timestamps for playbooks

---

auth/clerk_client.go

chore: default clerk role to viewer

---

api/global.go
jobs/jobs.go

resolves: https://github.com/flanksource/incident-commander/issues/671

feat: disable incidents job if incidents.disable=true

---

cmd/root.go
cmd/server.go

resolves: https://github.com/flanksource/incident-commander/issues/695

feat: add `--disable-kubernetes` flag

---

notification/shoutrrr.go
playbook/actions/exec.go

resolves: https://github.com/flanksource/incident-commander/issues/723

fix: exec action and notification

---

events/event_queue.go
notification/notification_test.go
notification/shoutrrr.go
notification/shoutrrr_test.go
notification/suite_test.go

resolves: https://github.com/flanksource/incident-commander/issues/729

fix: event consumers

---

go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
playbook/jobs.go
playbook/run_consumer.go
playbook/runner.go

resolves: https://github.com/flanksource/mission-control/issues/808

feat: delay the action on the host itself

---

db/playbooks.go
playbook/playbook.go
playbook/playbook_test.go
playbook/runner.go

resolves: https://github.com/flanksource/mission-control/issues/813

fix: playbook run status

---

go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
notification/events.go
notification/send.go

- fix notification templates for component related events
- handle errors in the notification filter
- fixes sync event consumer duplicates with https://github.com/flanksource/postq/pull/7 (resolves: https://github.com/flanksource/mission-control/issues/814)

fix: event queue

---

go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
jobs/jobs.go
jobs/upstream.go
upstream/controllers.go
upstream/upstream_test.go

resolves: https://github.com/flanksource/duty/issues/520

feat: agent last seen and last received timestamps

---

api/v1/playbook_actions.go
go.mod
go.sum
pkg/clients/git/connectors/connectors.go
pkg/clients/git/connectors/connectors_test.go
pkg/clients/git/connectors/git_access_token.go
pkg/clients/git/connectors/git_ssh.go
pkg/clients/git/git.go
playbook/actions/gitops.go
playbook/actions/gitops_test.go

resolves: https://github.com/flanksource/mission-control/issues/791
merge after: https://github.com/flanksource/mission-control/pull/816

feat: gitops actions pull requests for GitLab

---

jobs/jobs.go
jobs/upstream.go

Already present in canary checker
https://github.com/flanksource/canary-checker/blob/bd7d176450e17043a650b5777d91dd8665cda86c/pkg/jobs/canary/sync_upstream.go#L65-L79

chore: remove sync check statuses job

---

jobs/jobs.go

chore: add sync config cache job

---

api/v1/playbook_actions.go

chore: template url and connection in gitops action

---

playbook/runner.go

chore: playbooks steps should not run after a step failure

---

cmd/server.go
db/middleware.go
db/middleware_test.go
db/suite_test.go
go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum

resolves: https://github.com/flanksource/mission-control/issues/879

feat: postgREST middleware for filter query

---

go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
playbook/actions/actions.go

Depends on: https://github.com/flanksource/duty/pull/592

chore: use config template env for playbook

---

go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum

resolves: https://github.com/flanksource/duty/issues/594

chore: bump duty

---

fixtures/playbooks/gitops.yaml
playbook/actions/actions.go
playbook/runner.go

resolves: https://github.com/flanksource/mission-control/issues/886

feat: add user variable to playbook templates

---

db/properties.go
echo/serve.go

resolves: https://github.com/flanksource/mission-control/issues/859

feat: properties endpoint

---

api/v1/playbook_actions.go
events/event_queue.go
go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
playbook/actions/exec.go

- make artifacts path templatable.
- fix notification async handler errors
- throw error if anything goes wrong when saving artifact

fix: artifacts

---

playbook/actions/actions.go
playbook/controllers.go
playbook/playbook.go
playbook/run_consumer.go
playbook/runner.go

Required by the "Request namespace access" playbook to be used in the rolebinding name.

feat: make playbook & run objects accessible in templates

---

db/agents.go
playbook/runner.go

resolves: https://github.com/flanksource/mission-control/issues/946

fix: playbook action assigned to non existing agents should error

---

go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
incidents/evidence_script_cel.go
incidents/responder/comments_sync.go
incidents/responder/config_sync.go
incidents/rules.go
jobs/jobs.go
jobs/upstream.go

* add stale job history cleanup job
merge after: https://github.com/flanksource/duty/pull/666
resolves: https://github.com/flanksource/duty/issues/663

feat: connection string format change

---

go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum

resolves: https://github.com/flanksource/mission-control/issues/980
This PR includes the updated duty version which handles the unique constraint on the playbook name and connection name.

fix: playbooks & connections controller unique constraint

---

notification/events.go
notification/send.go

resolves: https://github.com/flanksource/duty/issues/726

fix: check_status query for check pass/fail events in notification

---

api/v1/playbook_actions.go

fix: template user.name and user.email in gitops actions

---

api/event.go
notification/events.go
notification/send.go
playbook/events.go

resolves: https://github.com/flanksource/mission-control/issues/998

feat: config health notifications & playbook event triggers

---

jobs/event_queue.go

remove stuff related to `push_queue.create`

fix: success reporting in event queue cleanup job

---

db/notifications.go
go.mod
go.sum
notification/events.go
notification/ratelimit.go

resolves: https://github.com/flanksource/mission-control/issues/1001

feat: sliding window rate limiter on notifications

---

playbook/actions/actions.go
playbook/runner.go

resolves: https://github.com/flanksource/mission-control/issues/1013

feat: add agent details in playbook templates

---

playbook/actions/actions.go
playbook/actions/gitops_test.go
playbook/controllers.go
playbook/playbook.go
playbook/playbook_test.go
playbook/runner.go

resolves: https://github.com/flanksource/mission-control/issues/1014

feat: full resource object on playbook templates

---

notification/events.go

resolves: https://github.com/flanksource/mission-control/issues/993

fix: stale statuses for checks & stale health fro configs & components on notification templates

---

echo/serve.go

Fixes: https://github.com/flanksource/azure-production/issues/101

chore: ignore 404 for prometheus

---

db/init.go

resolves: https://github.com/flanksource/mission-control/issues/1037

feat: set statement timeouts after migration

---

api/global.go
cmd/root.go
main.go

related: https://github.com/flanksource/duty/issues/796

feat: set the upstream client user agent to the app build version

---

playbook/actions/actions.go
playbook/runner.go
playbook/template.go

resolves: https://github.com/flanksource/mission-control/issues/1053

feat: auto inject gitops env vars when the playbook has gitops action

---

db/playbooks.go
playbook/controllers.go
playbook/playbook.go
playbook/run_consumer.go
playbook/runner.go

resolves: https://github.com/flanksource/mission-control/issues/1071

feat: playbook namespace

---

.github/workflows/release.yml

chore: add ecr release

---

catalog/controllers.go

https://github.com/flanksource/flanksource-ui/pull/2012#issuecomment-2167654161

fix: use POST for /catalog/changes

---

db/agents.go
db/evidences.go
echo/serve.go
push/topology.go

Depends on: https://github.com/flanksource/duty/pull/858
Fixes: Fixes: https://github.com/flanksource/canary-checker/issues/1909

feat: push topology

---

jobs/job_history_cleanup.go
jobs/jobs.go

Blocked on: https://github.com/flanksource/duty/pull/871

feat: cleanup agent job history

---

db/connections.go

fix: url setting for sql and mongo connection

---

api/v1/playbook_types.go
config/crds/mission-control.flanksource.com_playbooks.yaml
playbook/controllers.go
playbook/playbook.go
playbook/playbook_test.go

resolves: https://github.com/flanksource/mission-control/issues/1208

feat: support required parameters

---

playbook/playbook.go
playbook/runner.go

resolves: https://github.com/flanksource/mission-control/issues/1238

feat: save playbook run as config change

---

api/v1/playbook_types.go
cmd/server.go

Blocked on: https://github.com/flanksource/duty/pull/949

chore: add playbook title

---

notification/events.go
notification/notification_test.go

Blocked on: https://github.com/flanksource/mission-control/pull/1312
Fixes: https://github.com/flanksource/mission-control/issues/1297

feat: add repeat interval check for notifications

---

notification/events.go
notification/send.go
notification/slack.go
notification/template.go
notification/templates/check.failed
notification/templates/check.passed
notification/templates/component.health
notification/templates/config.db.update
notification/templates/config.health

- config.created, config.updated, config.deleted
- `config.<health>`
- `component.<health>`

feat: slack notification templates

---

notification/template.go
notification/templates/check.failed
notification/templates/check.passed
notification/templates/component.health
notification/templates/config.db.update
notification/templates/config.health

resolves: https://github.com/flanksource/mission-control/issues/1329

fix: slack labels in section limit

---

auth/kratos_client.go
echo/people.go
echo/serve.go
echo/users.go
go.mod
go.sum
rbac/init.go
rbac/objects.go
rbac/policies.yaml
rbac/policy.go

resolves: https://github.com/flanksource/mission-control/issues/1346
merge after: https://github.com/flanksource/duty/pull/1012

feat: /people/update endpoint

---

auth/kratos_client.go
notification/notification_test.go

resolves: https://github.com/flanksource/mission-control/issues/1350

fix: sync admin identity & person on startup

---

api/event.go
notification/events.go
notification/send.go
playbook/events.go

resolves: https://github.com/flanksource/config-db/issues/736

feat: handle config.changed event

---

db/middleware.go
db/middleware_test.go

This test kept failing.
the expected time were off by 1-3 seconds

fix: pass current time to datemath parser

---

echo/people.go
echo/serve.go
go.mod
go.sum

merge after: https://github.com/flanksource/duty/pull/1044
resolves: https://github.com/flanksource/mission-control/issues/1382

feat: delete user endpoint

---

db/notifications.go

resolves: https://github.com/flanksource/mission-control/issues/1394

feat: save name & namespace for notifications

---

notification/cel.go
notification/events.go
notification/template.go
notification/templates/check.failed
notification/templates/check.passed
notification/templates/component.health
notification/templates/config.db.update
notification/templates/config.health

resolves: https://github.com/flanksource/mission-control/issues/1393

feat: silence button for slack notifications

---

playbook/playbook_test.go

Added 
```go
if _, err := exec.LookPath("pwsh.exe"); err != nil {
return
}
```
to powershell test because test suite kept failing locally.

chore: refactor playbooks test

---

Dockerfile
cmd/playbook.go
playbook/runner/runner.go
playbook/testdata/agent-runner.yaml

resolves: https://github.com/flanksource/mission-control/issues/1428

fix: runsOn handling

---

playbook/run_consumer.go
playbook/runner/agent.go
playbook/runner/exec.go
playbook/runner/runner.go

resolves: https://github.com/flanksource/mission-control/issues/1360

fix: playbook run duplicates

---

notification/context.go
notification/events.go
notification/notification_test.go

resolves: https://github.com/flanksource/mission-control/issues/1447

fix: set proper status on notification send history

---

playbook/playbook_test.go
playbook/test.properties
playbook/testdata/agent-runner.yaml

resolves: https://github.com/flanksource/mission-control/issues/1264

test: multiple runners

---

playbook/actions/gitops.go

resolves: https://github.com/flanksource/mission-control/issues/1433

feat: Path validation on GitOps playbook action

---

api/v1/playbook_types.go
playbook/approval.go
playbook/playbook.go

resolves: https://github.com/flanksource/mission-control/issues/1468

feat: improve playbook permission error

---

auth/controllers.go

resolves: https://github.com/flanksource/mission-control/issues/1484

fix: save role for newly invited user

---

go.mod
go.sum
jobs/catalog.go
jobs/jobs.go

Depends on: https://github.com/flanksource/duty/pull/1116

chore: add refresh catalog job for 3d view

---

agent/agent.go
auth/kratos.go
db/agents.go

Fixes: https://github.com/flanksource/mission-control/issues/1371

fix: set user object correctly in kratos auth

---

api/v1/playbook_actions.go
api/v1/playbook_types.go
playbook/actions/actions.go

chore: add templating to playbook and update template env

---

db/playbooks.go
go.mod
go.sum
playbook/events.go
playbook/playbook.go

resolves: https://github.com/flanksource/mission-control/issues/1506

chore: rename Pending to PendingApproval on playbook run status

---

notification/events.go

related: https://github.com/flanksource/mission-control/issues/1515
related: https://github.com/flanksource/mission-control/issues/1516

fix: notification wait for health evaluation

---

pkg/clients/git/connectors/git_access_token.go

resolves: https://github.com/flanksource/mission-control/issues/1564

fix: panic on git client creation on empty access token

---

push/topology.go

Fixes: https://github.com/flanksource/mission-control/issues/1583

fix: delete push topology component in chunks

---

cmd/server.go

resolves: https://github.com/flanksource/mission-control/issues/1563

feat: playbook table sync

---

db/notifications.go
db/notifications_test.go
notification/events.go
notification/silence.go

resolves: https://github.com/flanksource/mission-control/issues/1590

feat: filter on notification silence

---

connection/check.go
notification/send.go
notification/slack.go

resolves: https://github.com/flanksource/mission-control/issues/1613

feat: improve slack error

---

notification/events.go

resolves: https://github.com/flanksource/mission-control/issues/1636

fix: increase dedup window for unsent notifications

---

playbook/runner/agent.go
upstream/controllers.go

resolves: https://github.com/flanksource/mission-control/issues/1673

fix: handle error when issuing playbook actions to agents

---

go.mod
go.sum
notification/context.go
notification/send.go

resolves: https://github.com/flanksource/mission-control/issues/1684

feat: save notification recipient

---

notification/slack.go

resolves: https://github.com/flanksource/mission-control/issues/1705

fix: save slack message body to send history

---

rbac/adapter/permission.go
rbac/model.ini
rbac/policy.go
rbac/rbac_test.go

until [RLS](https://github.com/flanksource/mission-control/pull/1560) gets merged

fix: RBAC policy definition changes temp fix

---

db/notifications.go
notification/events.go

resolves: https://github.com/flanksource/mission-control/issues/1626

feat: save the silence that silence a notification

---

catalog/controllers.go
db/permissions.go

fix: setting RLS JSON payload in postgresql parameter

fix(RLS): Save tags & agents from CRD

---

rbac/adapter/permission.go

Just having the following RBAC policy will fail the ABAC permission test.
| p   | subject                              | object    | action       | effect | condition                                                                        |
| --- | ------------------------------------ | --------- | ------------ | ------ | -------------------------------------------------------------------------------- |
| p   | 8fcd6458-881b-450c-ac2a-f38b3761a443 | playbooks | playbook:run | allow  |                                                                                  |
This casbin request will pass.
```
RBAC: 8fcd6458-881b-450c-ac2a-f38b3761a443, playbooks, playbook:run
```
This will fail as there's no policy with the matching object
```
ABAC: 8fcd6458-881b-450c-ac2a-f38b3761a443, {playbook: …
```

fix: map RBAC to ABAC

---

rbac/adapter/permission.go

we added mapping of global permission on playbooks to ABAC permission [here](https://github.com/flanksource/mission-control/pull/1764).
We also need that for catalogs & components.

fix: global object permission -> ABAC for configs & components

---

playbook/actions/ai.go

Return the summary of the diagnosis when format=recommendPlaybooks (not just the buttons)

fix: AI action recommend playbook prompt

---

playbook/runner/agent.go

resolves: https://github.com/flanksource/mission-control/issues/1804

fix: handle template errors for actions for agents

---

api/v1/connection_types.go
api/v1/notification_types.go
go.mod
go.sum

merge after: https://github.com/flanksource/kopper/pull/19

feat: implement kopper interface to manage status subresource

---

pkg/clients/git/connectors/connectors.go
pkg/clients/git/connectors/connectors_test.go
pkg/clients/git/connectors/git_access_token.go
playbook/actions/gitops.go

fix: handle managed github/gitlab in playbook actions

---

notification/job.go

resolves: https://github.com/flanksource/mission-control/issues/1838

fix: pending notification looping on error

---

playbook/actions/ai.go

[Blockkit](https://app.slack.com/block-kit-builder/TSS2SUEVA#%7B%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%F0%9F%9A%A8%20Deployment%20Issue%20Detected%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22The%20deployment%20%60bad-image-deployment%60%20is%20experiencing%20issues%20due%20to%20an%20incorrect%20image%20name,%20causing%20an%20%60ImagePullBackOff%60%20error.%22%7D%7D,%7B%22type%22:%22section%22,%22fields%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Deployment*:%20bad-image-deployment%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Namespace*:%20mc%22%7D%5D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Labels*%22%7D,%22fields%22:%5 …

feat: update prompt for playbook recommender

---

cmd/server.go
vars/vars.go

Depends on: https://github.com/flanksource/duty/pull/1342

chore: add support for disable rls flag

---

notification/cel.go
notification/events.go
notification/templates/config.health

resolves: https://github.com/flanksource/mission-control/issues/1862

feat: show recent events in config notification

---

cmd/catalog.go
jobs/jobs.go

related: https://github.com/flanksource/duty/issues/1238

feat: case insensitive suffix based type query

---

auth/middleware.go

chore: add api.SystemUserID to superusers

---

notification/notification_test.go

resolves: https://github.com/flanksource/mission-control/issues/1898

test: notification recent events

---

notification/events.go

resolves: https://github.com/flanksource/mission-control/issues/1896

feat(repeatInterval): only considered sent notifications

---

db/permissions.go
echo/serve.go
playbook/actions/actions.go
playbook/controllers.go
playbook/playbook.go
playbook/playbook_test.go
playbook/suite_test.go
playbook/testdata/echo.yaml
playbook/testdata/permissions/allow-config-read.yaml
playbook/testdata/permissions/allow-playbook.yaml
playbook/testdata/permissions/deny-config-read.yaml
playbook/testdata/permissions/deny-playbook.yaml

dependsOn: https://github.com/flanksource/duty/pull/1271
resolves: https://github.com/flanksource/mission-control/issues/1756

fix: check `read` permission on playbook resources

---

.gitignore
fixtures/playbooks/postgres-backup.yaml
playbook/runner/template.go

resolves: https://github.com/flanksource/mission-control/issues/1934

fix: slack template functions in notification playbook action

---

Makefile
go.mod
go.sum
playbook/controllers.go
playbook/playbook_test.go
playbook/testdata/my-kube-config.yaml

resolves: https://github.com/flanksource/mission-control/issues/1911

feat: Playbook cancellation

---

cmd/server.go
db/connections.go
db/incidents.go
db/notifications.go
db/permissions.go
db/playbooks.go
go.mod
go.sum
notification/silence.go

resolves: https://github.com/flanksource/mission-control/issues/1949

feat: reconcile deleted CRDs

---

cmd/server.go

fix: initalize notification reconciler

---

api/v1/playbook_actions.go
api/v1/playbook_types.go
config/crds/mission-control.flanksource.com_playbooks.yaml
config/schemas/playbook-spec.schema.json
config/schemas/playbook.schema.json
echo/serve.go
jobs/jobs.go
jobs/playbook.go
playbook/jobs.go
playbook/playbook.go
playbook/run_consumer.go
playbook/runner/runner.go
vars/vars.go

resolves: https://github.com/flanksource/mission-control/issues/1956

feat: Playbook run timeout

---

playbook/actions/http.go

* Improve the action result struct so it's better displayed in the UI
Instead of showing two tabs - code & headers we show one

feat(http action): error when connection isn't provided

---

playbook/actions/notification.go
playbook/runner/exec.go

resolves: https://github.com/flanksource/flanksource-ui/issues/2517

feat: save results in notification action

---

go.mod
go.sum
notification/events.go
playbook/events.go
playbook/jobs.go
playbook/playbook.go

resolves: https://github.com/flanksource/mission-control/issues/1986

fix: timing out playbook runs must re-initiate the parent notification

---

playbook/events.go
playbook/playbook.go
playbook/runner/runner.go
playbook/testdata/permissions/deny-echo-playbook.yaml
playbook/testdata/permissions/deny-playbook-on-config.yaml

dependsOn: https://github.com/flanksource/duty/pull/1393

fix: playbooks must run as subject=playbook not the service/user that triggered it

---

db/notifications.go
go.mod
go.sum
notification/job.go
notification/notification_test.go

dependsOn: https://github.com/flanksource/duty/pull/1395

feat: Dedup skipped notifications

---

db/notifications.go
go.mod
notification/events.go
notification/send.go
notification/suite_test.go
playbook/suite_test.go

resolves: https://github.com/flanksource/mission-control/issues/2019

feat: save notification body and recipients for unsent notifications

---

playbook/actions/ai.go
playbook/actions/ai_slack.go

resolves: https://github.com/flanksource/mission-control/issues/1982

feat: grouped resources in notifications from playbook

---

cmd/server.go

resolves: https://github.com/flanksource/duty/issues/1402
when new playbook/notification is created (or deleted), we need to add/remove the corresponding casbin policy.

fix: re-evaluate permission when playbooks & notifications are created/deleted

---

api/event.go
db/notifications.go
go.mod
go.sum
notification/events.go
notification/notification_test.go

resolves: https://github.com/flanksource/mission-control/issues/2021

feat: remove resources from group once resolved

---

playbook/playbook.go

use structTemplater as that supports `{{}}` & `$()`

fix: templating fromConfigItem with $()

---

go.mod
go.sum
llm/cost.go
llm/cost_test.go
llm/gemini.go
llm/llm.go
playbook/actions/ai.go

resolves: https://github.com/flanksource/mission-control/issues/1829

feat: LLM cost

---

.gitignore
api/v1/notification_types.go
config/crds/mission-control.flanksource.com_connections.yaml
config/crds/mission-control.flanksource.com_notifications.yaml
config/schemas/connection.schema.json
config/schemas/notification.schema.json
db/notifications.go
go.mod
notification/events.go
pkg/clients/git/connectors/git_access_token.go
pkg/clients/git/connectors/git_ssh.go
playbook/actions/ai_slack.go
playbook/actions/gitops.go
playbook/actions/pod.go
utils/dir.go

The db had groupByInterval setup, but the CRD didn't.

feat: notification groupByInterval CRD

---

api/v1/playbook_actions.go
playbook/actions/ai.go

only set a default model after populating connection cuz then we'll have the backend

fix: set defaults after population

---

.gitignore
playbook/actions/ai.go

- don't use marshalIndent as that adds up a lot of tab and new line characters

fix: duplicate artifacts in AI action

---

playbook/actions/ai_slack.go

resolves: https://github.com/flanksource/mission-control/issues/2126

fix: slack invalid blocks

---

.github/workflows/release.yml

related: https://forums.docker.com/t/unexpected-missing-content-length-header-for-request/145907

fix: bump Publish-Docker-Github-Action

---

application/job_test.go
application/scraper.go

resolves: https://github.com/flanksource/mission-control/issues/2132

feat: generate GCP scraper

---

notification/events.go

* include the resource id as well
related: https://github.com/flanksource/mission-control/issues/2144

fix: notification silence error improvement

---

agent/agent.go
agent/controllers.go
api/agent.go
auth/tokens.go
db/people.go
echo/serve.go

Fixes: #2145 
Fixes: https://github.com/flanksource/mission-control/issues/1243

feat: add option to generate new token for existing agent

---

notification/events.go

resolves: https://github.com/flanksource/mission-control/issues/2191

fix: improve rate limited notifications log

---

.gitignore
api/v1/view_types.go
api/view.go
config/crds/mission-control.flanksource.com_views.yaml
config/schemas/view.schema.json
go.mod
go.sum
tests/e2e/views_test.go
views/run.go
views/table.go
views/testdata/cache-test-view.yaml
views/testdata/kubernetes-node-view.yaml
views/testdata/pod-view.yaml
views/views_test.go

depends on: https://github.com/flanksource/duty/pull/1516

feat: column attributes

---

mcp/health_checks.go
mcp/server.go

feat(mcp): add health check tools

---

api/view.go
views/run.go
views/table.go

fix: view variables

---

api/view_panel.go
config/crds/mission-control.flanksource.com_views.yaml
fixtures/views/pipelines.yaml

https://github.com/flanksource/flanksource-ui/issues/2626

feat(view): duration panel

---

db/agents.go

We were selecting the deleted agent by name.

fix(agents): ignore deleted agents

---

agent/agent.go
api/agent.go
auth/controllers.go
auth/tokens.go
cmd/token.go
db/people.go
echo/kube_config_download.go

Fixes: https://github.com/flanksource/mission-control/issues/2369

feat: add option to auto renew token
